name: Playwright Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - closed

  schedule:
    - cron: "0 17 * * *"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  playwright-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      PRACTICE_USERNAME: ${{ secrets.PRACTICE_USERNAME }}
      PRACTICE_PASSWORD: ${{ secrets.PRACTICE_PASSWORD }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22 # new version of Node.js
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run tests:headless

      - name: Upload Playwright reports and test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-and-results
          path: |
            playwright-report/
            test-results/
          if-no-files-found: warn
          retention-days: 14
